using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Geodo.RSS.MIF.UI
{
    public enum masExcelDrawStatType
    {
        xl3DArea,
        xl3DAreaStacked,
        xl3DAreaStacked100,
        xl3DBarClustered,
        xl3DBarStacked,
        xl3DBarStacked100,
        xl3DColumn,
        xl3DColumnClustered,
        xl3DColumnStacked,
        xl3DColumnStacked100,
        xl3DLine,
        xl3DPie,
        xl3DPieExploded,
        xlArea,
        xlAreaStacked,
        xlAreaStacked100,
        xlBarClustered,
        xlBarOfPie,
        xlBarStacked,
        xlBarStacked100,
        xlBubble,
        xlBubble3DEffect,
        xlColumnClustered,
        xlColumnStacked,
        xlColumnStacked100,
        xlConeBarClustered,
        xlConeBarStacked,
        xlConeBarStacked100,
        xlConeCol,
        xlConeColClustered,
        xlConeColStacked,
        xlConeColStacked100,
        xlCylinderBarClustered,
        xlCylinderBarStacked,
        xlCylinderBarStacked100,
        xlCylinderCol,
        xlCylinderColClustered,
        xlCylinderColStacked,
        xlCylinderColStacked100,
        xlDoughnut,
        xlDoughnutExploded,
        xlLine,
        xlLineMarkers,
        xlLineMarkersStacked,
        xlLineMarkersStacked100,
        xlLineStacked,
        xlLineStacked100,
        xlPie,
        xlPieExploded,
        xlPieOfPie,
        xlPyramidBarClustered,
        xlPyramidBarStacked,
        xlPyramidBarStacked100,
        xlPyramidCol,
        xlPyramidColClustered,
        xlPyramidColStacked,
        xlPyramidColStacked100,
        xlRadar,
        xlRadarFilled,
        xlRadarMarkers,
        xlStockHLC,
        xlStockOHLC,
        xlStockVHLC,
        xlStockVOHLC,
        xlSurface,
        xlSurfaceTopView,
        xlSurfaceTopViewWireframe,
        xlSurfaceWireframe,
        /// <summary>
        /// 散点图
        /// </summary>
        xlXYScatter,
        xlXYScatterLines,
        xlXYScatterLinesNoMarkers,
        xlXYScatterSmooth,
        xlXYScatterSmoothNoMarkers
    }
}
