//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

using System.Drawing;
using System;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 

namespace GeoVis.GeoCore
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class PlaceMarkInfo
    {
        private long idField;

        private long pageIDField;

        private string nameField;

        private string scenenameField;

        private long scenePageIdField;

        private double longitudeField;

        private double latitudeField;

        private double altitudeField;

        private long modelIdField;

        private double rotXField;

        private double rotYField;

        private double rotZField;

        private double scaleXField;

        private double scaleYField;

        private double scaleZField;

        private string modefilenameField;

        private string modeNameField;

        private string descriptionField;

        private string formatField;
        public override string ToString()
        {
            return nameField;
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PageID
        {
            get
            {
                return this.pageIDField;
            }
            set
            {
                this.pageIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Scenename
        {
            get
            {
                return this.scenenameField;
            }
            set
            {
                this.scenenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ScenePageId
        {
            get
            {
                return this.scenePageIdField;
            }
            set
            {
                this.scenePageIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Altitude
        {
            get
            {
                return this.altitudeField;
            }
            set
            {
                this.altitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ModelId
        {
            get
            {
                return this.modelIdField;
            }
            set
            {
                this.modelIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double RotX
        {
            get
            {
                return this.rotXField;
            }
            set
            {
                this.rotXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double RotY
        {
            get
            {
                return this.rotYField;
            }
            set
            {
                this.rotYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double RotZ
        {
            get
            {
                return this.rotZField;
            }
            set
            {
                this.rotZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ScaleX
        {
            get
            {
                return this.scaleXField;
            }
            set
            {
                this.scaleXField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ScaleY
        {
            get
            {
                return this.scaleYField;
            }
            set
            {
                this.scaleYField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double ScaleZ
        {
            get
            {
                return this.scaleZField;
            }
            set
            {
                this.scaleZField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Modefilename
        {
            get
            {
                return this.modefilenameField;
            }
            set
            {
                this.modefilenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ModeName
        {
            get
            {
                return this.modeNameField;
            }
            set
            {
                this.modeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Format
        {
            get
            {
                return this.formatField;
            }
            set
            {
                this.formatField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class GeoMapInfo
    {

        private string layersField;

        private double minLatitudeField;

        private double maxLatitudeField;

        private double minLongtitudeField;

        private double maxLongtitudeField;

        private int widthField;

        private int heightField;

        private int scaleField;

        private int imgformatField;

        private string projectInfoField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Layers
        {
            get
            {
                return this.layersField;
            }
            set
            {
                this.layersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MinLatitude
        {
            get
            {
                return this.minLatitudeField;
            }
            set
            {
                this.minLatitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MaxLatitude
        {
            get
            {
                return this.maxLatitudeField;
            }
            set
            {
                this.maxLatitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MinLongtitude
        {
            get
            {
                return this.minLongtitudeField;
            }
            set
            {
                this.minLongtitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double MaxLongtitude
        {
            get
            {
                return this.maxLongtitudeField;
            }
            set
            {
                this.maxLongtitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Scale
        {
            get
            {
                return this.scaleField;
            }
            set
            {
                this.scaleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Imgformat
        {
            get
            {
                return this.imgformatField;
            }
            set
            {
                this.imgformatField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ProjectInfo
        {
            get
            {
                return this.projectInfoField;
            }
            set
            {
                this.projectInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class PlaceInfo
    {

        private string placeNameField;

        private double longitudeField;

        private double latitudeField;

        private string pageTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PlaceName
        {
            get
            {
                return this.placeNameField;
            }
            set
            {
                this.placeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double Latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageType
        {
            get
            {
                return this.pageTypeField;
            }
            set
            {
                this.pageTypeField = value;
            }
        }
    }

    public class ImageInfo
    {

        private long pageIDField;

        private string fullPathField;

        private double minLatitudeField;

        private double maxLatitudeField;

        private double minLongtitudeField;

        private double maxLongtitudeField;

        private int widthField;

        private int heightField;

        private int bandsField;

        private int datatypeField;

        private int imgformatField;

        private string projectInfoField;

        private System.DateTime imageryDateTimeField;

        private System.DateTime postDateTimeField;

        private string descriptionField;

        private bool nginx;

        public bool Nginx
        {
            get { return nginx; }
            set { nginx = value; }
        }

        private string transParam;

        public string TransParam
        {
            get { return transParam; }
            set { transParam = value; }
        }

        private double transMinLong;

        public double TransMinLong
        {
            get { return transMinLong; }
            set { transMinLong = value; }
        }

        private double transMinLat;

        public double TransMinLat
        {
            get { return transMinLat; }
            set { transMinLat = value; }
        }

        private double transMaxLong;

        public double TransMaxLong
        {
            get { return transMaxLong; }
            set { transMaxLong = value; }
        }

        private double transMaxLat;

        public double TransMaxLat
        {
            get { return transMaxLat; }
            set { transMaxLat = value; }
        }


        /// <remarks/>

        public long PageID
        {
            get
            {
                return this.pageIDField;
            }
            set
            {
                this.pageIDField = value;
            }
        }

        /// <remarks/>

        public string FullPath
        {
            get
            {
                return this.fullPathField;
            }
            set
            {
                this.fullPathField = value;
            }
        }

        /// <remarks/>

        public double MinLatitude
        {
            get
            {
                return this.minLatitudeField;
            }
            set
            {
                this.minLatitudeField = value;
            }
        }

        /// <remarks/>

        public double MaxLatitude
        {
            get
            {
                return this.maxLatitudeField;
            }
            set
            {
                this.maxLatitudeField = value;
            }
        }

        /// <remarks/>

        public double MinLongtitude
        {
            get
            {
                return this.minLongtitudeField;
            }
            set
            {
                this.minLongtitudeField = value;
            }
        }

        /// <remarks/>

        public double MaxLongtitude
        {
            get
            {
                return this.maxLongtitudeField;
            }
            set
            {
                this.maxLongtitudeField = value;
            }
        }

        /// <remarks/>

        public int Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>

        public int Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>

        public int Bands
        {
            get
            {
                return this.bandsField;
            }
            set
            {
                this.bandsField = value;
            }
        }

        /// <remarks/>

        public int Datatype
        {
            get
            {
                return this.datatypeField;
            }
            set
            {
                this.datatypeField = value;
            }
        }

        /// <remarks/>

        public int Imgformat
        {
            get
            {
                return this.imgformatField;
            }
            set
            {
                this.imgformatField = value;
            }
        }

        /// <remarks/>

        public string ProjectInfo
        {
            get
            {
                return this.projectInfoField;
            }
            set
            {
                this.projectInfoField = value;
            }
        }

        /// <remarks/>

        public System.DateTime ImageryDateTime
        {
            get
            {
                return this.imageryDateTimeField;
            }
            set
            {
                this.imageryDateTimeField = value;
            }
        }

        /// <remarks/>

        public System.DateTime PostDateTime
        {
            get
            {
                return this.postDateTimeField;
            }
            set
            {
                this.postDateTimeField = value;
            }
        }

        /// <remarks/>

        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        private string thumbStr;

        public string ThumbStr
        {
            get { return thumbStr; }
            set { thumbStr = value; }
        }

        public Image Thumb
        {
            get
            {
                if (!string.IsNullOrEmpty(thumbStr))
                {
                    byte[] bytes = Convert.FromBase64String(thumbStr);
                    System.IO.MemoryStream ms = new System.IO.MemoryStream(bytes);
                    return Image.FromStream(ms);
                }
                else
                    return null;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class Page
    {

        private long pageIDField;

        private string pageNsField;

        private string pageTitleField;

        private string pageLongTitleField;

        private string pageTypeField;

        private string pageTextField;

        private string pageTitleFragsField;

        private string pageTextFragsField;

        private string pageScoreField;

        public override string ToString()
        {
            return PageTitle;
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long PageID
        {
            get
            {
                return this.pageIDField;
            }
            set
            {
                this.pageIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageNs
        {
            get
            {
                return this.pageNsField;
            }
            set
            {
                this.pageNsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageTitle
        {
            get
            {
                return this.pageTitleField;
            }
            set
            {
                this.pageTitleField = value;
            }
        }

        /// <remarks/>

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageLongTitle
        {
            get
            {
                return this.pageLongTitleField;
            }
            set
            {
                this.pageLongTitleField = value;
            }
        }

        [System. Xml. Serialization. XmlAttributeAttribute()]
        public string PageType
        {
            get
            {
                return this.pageTypeField;
            }
            set
            {
                this.pageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageText
        {
            get
            {
                return this.pageTextField;
            }
            set
            {
                this.pageTextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageTitleFrags
        {
            get
            {
                return this.pageTitleFragsField;
            }
            set
            {
                this.pageTitleFragsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageTextFrags
        {
            get
            {
                return this.pageTextFragsField;
            }
            set
            {
                this.pageTextFragsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PageScore
        {
            get
            {
                return this.pageScoreField;
            }
            set
            {
                this.pageScoreField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public class POIInfo
    {
        public POIInfo()
        {

        }

        public POIInfo(string name, long layerId, long pageTypeID, GeoCoord geo, string description, string region, string wikilink)
        {
            this.nameField = name;
            this.pos = geo;
            this.descriptionField = description;
            this.areaField = region;
            this.wikilinkField = wikilink;
            this.layerID = layerId;
            this.pageTypeID = pageTypeID;
        }

        private long layerID;

        public long LayerID
        {
            get { return layerID; }
            set { layerID = value; }
        }

        private long pageTypeID;

        public long PageTypeID
        {
            get { return pageTypeID; }
            set { pageTypeID = value; }
        }

        private long pidField;

        private GeoCoord pos;

        public GeoCoord Pos
        {
            get { return pos; }
            set { pos = value; }
        }

        private string nameField;

        private string descriptionField;

        private string areaField;

        private string wikilinkField;

        /// <remarks/>
        public long Id
        {
            get
            {
                return this.pidField;
            }
            set
            {
                this.pidField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string Region
        {
            get
            {
                return this.areaField;
            }
            set
            {
                this.areaField = value;
            }
        }

        /// <remarks/>
        public string Wikilink
        {
            get
            {
                return this.wikilinkField;
            }
            set
            {
                this.wikilinkField = value;
            }
        }
    }

    public class CommonModelInfo
    {
        private long wikiPageID;

        public long WikiPageID
        {
            get { return wikiPageID; }
            set { wikiPageID = value; }
        }

        private int modelID;

        public int ModelID
        {
            get
            {
                return modelID;
            }
            set
            {
                modelID = value;
            }
        }

        private int categoryID;

        public int CategoryID
        {
            get { return categoryID; }
            set { categoryID = value; }
        }

        private string modelfilename;

        public string Modelfilename
        {
            get
            {
                return modelfilename;
            }
            set
            {
                modelfilename = value;
            }
        }

        private string modelName;

        public string ModelName
        {
            get
            {
                return modelName;
            }
            set
            {
                modelName = value;
            }
        }

        private string description;

        public string Description
        {
            get
            {
                return description;
            }
            set
            {
                description = value;
            }
        }

        private string format;

        public string Format
        {
            get
            {
                return format;
            }
            set
            {
                format = value;
            }
        }

        private string thumbStr;

        public string ThumbStr
        {
            get { return thumbStr; }
            set { thumbStr = value; }
        }

        public byte[] Thumb
        {
            get
            {
                if (!string.IsNullOrEmpty(thumbStr))
                {
                    byte[] bytes = Convert.FromBase64String(thumbStr);
                    return bytes;
                }
                else
                    return null;
            }
        }

        private string dataStr;

        public string DataStr
        {
            get { return dataStr; }
            set { dataStr = value; }
        }

        public byte[] Data
        {
            get
            {
                if (!string.IsNullOrEmpty(dataStr))
                {
                    byte[] bytes = Convert.FromBase64String(dataStr);
                    return bytes;
                }
                else
                    return null;

            }
        }

    }

    public class POIType
    {
        private long id;

        public long Id
        {
            get { return id; }
            set { id = value; }
        }
        private string name;

        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        public POIType()
        { }
    }

    public class POIImage
    {
        private long id;

        public long Id
        {
            get { return id; }
            set { id = value; }
        }
        private string name;

        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        private string imagestr;

        public string Imagestr
        {
            get { return imagestr; }
            set { imagestr = value; }
        }

        public Image Icon
        {
            get
            {
                if (!string.IsNullOrEmpty(imagestr))
                {
                    byte[] bytes = Convert.FromBase64String(imagestr);
                    System.IO.MemoryStream ms = new System.IO.MemoryStream(bytes);
                    return (Bitmap)Bitmap.FromStream(ms);
                }
                else
                    return null;

            }
        }

        public POIImage()
        {

        }

    }


    public class ImageSample
    {
        private long pageID;

        public long PageID
        {
            get { return pageID; }
            set { pageID = value; }
        }

        private double confidence;

        public double Confidence
        {
            get { return confidence; }
            set { confidence = value; }
        }

        private DateTime date;

        public DateTime Date
        {
            get { return date; }
            set { date = value; }
        }

        private string imagestr;

        public string ImageStr
        {
            get { return imagestr; }
            set { imagestr = value; }
        }

        private long imagePageID;

        public long ImagePageID
        {
            get { return imagePageID; }
            set { imagePageID = value; }
        }


        private string convertPara;

        public string ConvertPara
        {
            get { return convertPara; }
            set { convertPara = value; }
        }

        private string recogResult;

        public string RecogResult
        {
            get { return recogResult; }
            set { recogResult = value; }
        }

        private string sampleGeoInfo;

        public string SampleGeoInfo
        {
            get { return sampleGeoInfo; }
            set { sampleGeoInfo = value; }
        }

        public Image ImageData
        {
            get
            {
                if (!string.IsNullOrEmpty(imagestr))
                {
                    byte[] bytes = Convert.FromBase64String(imagestr);
                    System.IO.MemoryStream ms = new System.IO.MemoryStream(bytes);
                    return Image.FromStream(ms);
                }
                else
                    return null;

            }
            //set
            //{
            //    if (value != null)
            //    {
            //        System.IO.MemoryStream ms = new System.IO.MemoryStream();
            //        value.Save(ms, value.RawFormat);
            //        this.imagestr = Convert.ToBase64String(ms.ToArray());
            //    }
            //}
        }

        public ImageSample()
        {

        }


    }

    public class QueryCondition
    {
        private string _name;

        public string Name
        {
            get { return _name; }
            set { _name = value; }
        }

        private string _operater;

        public string Operator
        {
            get { return _operater; }
            set { _operater = value; }
        }

        private string _value;

        public string Value
        {
            get { return _value; }
            set { _value = value; }
        }

        public QueryCondition()
        {

        }

        public QueryCondition(string name, string operater, string valueStr)
        {
            this._name = name;
            this._operater = operater;
            this._value = valueStr;
        }

        public override string ToString()
        {
            string text = _name + " " + _operater + " " + _value;
            return text;
        }
    }
    public class ModelCategory
    {
        private int id;

        public int ID
        {
            get { return id; }
            set { id = value; }
        }

        private string name;

        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        public override string ToString()
        {
            return name;
        }

    }

    public class TaskInfo
    {
        private long pageID;

        public long PageID
        {
            get { return pageID; }
            set { pageID = value; }
        }

        private string taskName;

        public string TaskName
        {
            get { return taskName; }
            set { taskName = value; }
        }

        private DateTime begin;

        public DateTime Begin
        {
            get { return begin; }
            set { begin = value; }
        }

        private DateTime end;

        public DateTime End
        {
            get { return end; }
            set { end = value; }
        }

        private long targetID;

        public long TargetID
        {
            get { return targetID; }
            set { targetID = value; }
        }


        private string target;

        public string Target
        {
            get { return target; }
            set { target = value; }
        }

        private string targetDefn;

        public string TargetDefn
        {
            get { return targetDefn; }
            set { targetDefn = value; }
        }

        private string taskState;

        public string TaskState
        {
            get { return taskState; }
            set { taskState = value; }
        }

        private string xml;

        public string Xml
        {
            get { return xml; }
            set { xml = value; }
        }

        private long imageID;

        public long ImageID
        {
            get { return imageID; }
            set { imageID = value; }
        }

        private string thumStr;

        public string ThumbStr
        {
            get { return thumStr; }
            set { thumStr = value; }
        }

        public Image Thumb
        {
            get
            {
                if (!string.IsNullOrEmpty(thumStr))
                {
                    byte[] bytes = Convert.FromBase64String(thumStr);
                    System.IO.MemoryStream ms = new System.IO.MemoryStream(bytes);
                    return Image.FromStream(ms);
                }
                else
                    return null;

            }
        }


    }

    public class AircraftInfo
    {
        private long pageID;
        //页面ID
        public long PageID
        {
            get { return pageID; }
            set { pageID = value; }
        }

        private string name;
        //飞机名称或型号
        public string Name
        {
            get { return name; }
            set { name = value; }
        }

        private double winSpan;
        //翼款
        public double WinSpan
        {
            get { return winSpan; }
            set { winSpan = value; }
        }

        private double length;
        //机长
        public double Length
        {
            get { return length; }
            set { length = value; }
        }

        private double height;
        //高度
        public double Height
        {
            get { return height; }
            set { height = value; }
        }

        private string engine;
        //引擎
        public string Engine
        {
            get { return engine; }
            set { engine = value; }
        }

        private int enginNum;
        //引擎个数
        public int EnginNum
        {
            get { return enginNum; }
            set { enginNum = value; }
        }

        private string enginePos;
        //引擎位置
        public string EnginePos
        {
            get { return enginePos; }
            set { enginePos = value; }
        }

        private string wingType;
        //机翼类型
        public string WingType
        {
            get { return wingType; }
            set { wingType = value; }
        }

        private string empennage;
        //尾翼
        public string Empennage
        {
            get { return empennage; }
            set { empennage = value; }
        }

        private string alartRadar;
        //预警雷达
        public string AlartRadar
        {
            get { return alartRadar; }
            set { alartRadar = value; }
        }

        private string manuCountry;
        //制造国家
        public string ManuCountry
        {
            get { return manuCountry; }
            set { manuCountry = value; }
        }

        private string manufacturer;
        //制造商
        public string Manufacturer
        {
            get { return manufacturer; }
            set { manufacturer = value; }
        }

        private string useFor;
        //用途
        public string UseFor
        {
            get { return useFor; }
            set { useFor = value; }
        }

        private string thumStr;
        //缩略图的文本
        public string ThumStr
        {
            get { return thumStr; }
            set { thumStr = value; }
        }

        private string triViewStr;
        //三视图的文本
        public string TriViewStr
        {
            get { return triViewStr; }
            set { triViewStr = value; }
        }

        //缩略图
        public Image Thumb
        {
            get
            {
                if (!string.IsNullOrEmpty(thumStr))
                {
                    byte[] bytes = Convert.FromBase64String(thumStr);
                    System.IO.MemoryStream ms = new System.IO.MemoryStream(bytes);
                    return Image.FromStream(ms);
                }
                else
                    return null;
            }
        }

        //缩略图
        public Image TriView
        {
            get
            {
                if (!string.IsNullOrEmpty(triViewStr))
                {
                    byte[] bytes = Convert.FromBase64String(triViewStr);
                    System.IO.MemoryStream ms = new System.IO.MemoryStream(bytes);
                    return Image.FromStream(ms);
                }
                else
                    return null;
            }
        }
    }

}